// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1L0PHWU1HgB8VAF2q1fOcHYyDnq-On6c',
    appId: '1:669125815972:web:3ab12cef9e424767adc031',
    messagingSenderId: '669125815972',
    projectId: 'trepi-app',
    authDomain: 'trepi-app.firebaseapp.com',
    storageBucket: 'trepi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1WcFQgGN1yadoH4E6fUjn93Dy4Ftn8VA',
    appId: '1:669125815972:android:97083b9858b5ae44adc031',
    messagingSenderId: '669125815972',
    projectId: 'trepi-app',
    storageBucket: 'trepi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-IPM97T8AHEw_xKQMkKRYkoceknxuqiQ',
    appId: '1:669125815972:ios:ce0c91f1c8ae2915adc031',
    messagingSenderId: '669125815972',
    projectId: 'trepi-app',
    storageBucket: 'trepi-app.firebasestorage.app',
    iosClientId: '669125815972-nsqo6r2cucnt7oi8qpug6vckb8fveg7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.trepi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-IPM97T8AHEw_xKQMkKRYkoceknxuqiQ',
    appId: '1:669125815972:ios:ce0c91f1c8ae2915adc031',
    messagingSenderId: '669125815972',
    projectId: 'trepi-app',
    storageBucket: 'trepi-app.firebasestorage.app',
    iosClientId: '669125815972-nsqo6r2cucnt7oi8qpug6vckb8fveg7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.trepi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1L0PHWU1HgB8VAF2q1fOcHYyDnq-On6c',
    appId: '1:669125815972:web:e9d7535ba0cfe868adc031',
    messagingSenderId: '669125815972',
    projectId: 'trepi-app',
    authDomain: 'trepi-app.firebaseapp.com',
    storageBucket: 'trepi-app.firebasestorage.app',
  );
}
